# Set to author to set pr creater as assignee. Set to true to add random assignees to pull requests
addAssignees: author

# Set to true to add random reviewers to pull requests
# addReviewers: true

# A list of reviewers to be added to pull requests (GitHub user name)
# reviewers:
#   - reviewerA
#   - reviewerB
#   - reviewerC

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
# numberOfReviewers: 0

# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
  - wip