lenguage: node_js
node_js: 
  - "6.9"
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_AUTH_TOKEN"
  on:
    branch: master
    tags: true
